#!/usr/bin/env python3
"""
build_pathway_contexts.py
Generates pathway/contexts.json, a state-overlay on top of pathway/model.json.

WHY A SEPARATE FILE (not model.json)
model.json is the single source of truth for pathway BIOLOGY (nodes,
interactions, routes, loops) and must never be hand-edited -- see
build_pathway_model.py. Context weighting is a different kind of claim:
"how active is this already-curated interaction under Fed / Fasting /
Exercise", not "does this interaction exist". Keeping it in its own file
means model.json stays untouched and contexts.json can be regenerated,
diffed and validated independently.

STATE VOCABULARY (per edge / per node, within one context)
  active      -- this arm is currently firing / this node is up-weighted
  suppressed  -- this arm is currently quiet / this node is down-weighted
  unclear     -- genuinely ambiguous or under-characterised in this state,
                 NOT the same as "suppressed" -- see epistemic-labelling-pass
  (absent)    -- not evaluated for this context; renders identically to
                 today's baseline (folded into the existing .dim mechanism
                 in pathway.js, not a new visual channel)

ENCODING RULE (why this file only carries state, never colour/shape)
Pathway edge colour is reserved for EFFECT (--pw-act/--pw-inh/--pw-req/
--pw-bind) and dash-pattern+width is reserved for CERTAINTY (directness x
mechanistic confidence) -- see tier-palette-rule. Context state must not
collide with either, so pathway.js renders it as a separate underlay layer
(solid/dashed/dotted, neutral ink colour) plus a small text badge on nodes.
This file only ever emits the abstract state string; all rendering
decisions live in pathway.js.

FASTING is generated by MECHANICALLY MIRRORING Fed (active<->suppressed,
na/unclear untouched) rather than hand-curated a second time. This is a
deliberate simplification, documented here and in the on-page brief: it
models Fed and Fasting as the same fixed network with opposite arms lit,
which is the correct first-order reading for the arms curated below. Any
edge where that mirror is NOT a fair reading of the literature should be
special-cased in FASTING_OVERRIDE below rather than silently mirrored.

Exercise is NOT mirrored -- it is hand-curated because AMPK/mechanical
stress and the GF/AA arm do not sit at opposite ends of one axis the way
Fed/Fasting do.
"""
import json
import os
import sys

REPO = "/sessions/clever-vigilant-brown/mnt/Oliver biology Cowork"
MODEL_PATH = os.path.join(REPO, "pathway", "model.json")
OUT_PATH = os.path.join(REPO, "pathway", "contexts.json")

with open(MODEL_PATH, "r", encoding="utf-8") as f:
    MODEL = json.load(f)

ALL_EDGE_IDS = set(e["id"] for e in MODEL["interactions"])
ALL_NODE_IDS = set(n["id"] for n in MODEL["nodes"])

# ---------------------------------------------------------------------------
# FED -- hand-curated. Insulin/GF and amino acids both high, energy stress low.
# ---------------------------------------------------------------------------
FED_EDGES = {
    # amino-acid sensing arm -- fully engaged
    "LEU-SESN2": "active", "LEU-LARS": "active", "SESN2-GATOR2": "suppressed",
    "ARG-CASTOR1": "active", "CASTOR1-GATOR2": "suppressed",
    "SAM-SAMTOR": "active", "SAMTOR-GATOR1": "suppressed",
    "GATOR2-GATOR1": "active", "GATOR1-RAG": "suppressed",
    "LARS-RAG": "active", "SLC38A9-RAG": "active", "GLN-RAG": "active",
    "RAG-MTORC1": "active", "RHEB-MTORC1": "active",
    # growth-factor arm -- fully engaged
    "IGF1-PI3K": "active", "PI3K-AKT": "active", "AKT-TSC": "active",
    "AMPK-TSC": "suppressed", "AMPK-MTORC1": "suppressed",
    "TSC-RHEB": "suppressed", "AKT-PRAS40": "active", "PRAS40-MTORC1": "suppressed",
    "MTORC1-GRB10": "active", "GRB10-IGF1": "active",
    "S6K1-IRS1": "active", "IRS1-PI3K": "suppressed",
    "MTORC1-S6K1": "active",
    # energy arm -- quiet
    "STRESS-AMPK": "suppressed", "AMPK-ULK1": "suppressed", "AMPK-MITOPHAGY": "suppressed",
    # effector / output arm
    "MTORC1-4EBP1": "active", "MTORC1-TFEB": "active", "MTORC1-SREBP": "active",
    "MTORC1-ULK1": "active", "S6K1-PDCD4": "active",
    "4EBP1-EIF4E": "suppressed", "PDCD4-TRANSL": "suppressed",
    "EIF4E-TRANSL": "active", "TRANSL-MUSCLE": "active",
    "TFEB-AUTOPHAGY": "suppressed", "ULK1-AUTOPHAGY": "suppressed",
    "SREBP-LIPID": "active", "MTORC1-MITO": "active",
    "4EBP1-MITO": "suppressed", "MTORC1-NUCL": "active", "S6K1-NUCL": "active",
    "4EBP1-LONGEVITY": "suppressed", "S6K1-LONGEVITY": "active",
}
FED_NODES = {
    "Growth hormone / IGF-1 axis": "active", "Leucine": "active", "Arginine": "active",
    "S-adenosylmethionine (SAM)": "active", "Glutamine": "active",
    "PI3K": "active", "Akt/PKB": "active", "IRS-1 / IRS-2": "suppressed",
    "TSC1/TSC2": "suppressed", "Rheb": "active", "AMPK": "suppressed",
    "Rag GTPases": "active", "SLC38A9": "active",
    "GATOR1": "suppressed", "GATOR2": "active",
    "Sestrin2": "suppressed", "CASTOR1": "suppressed", "SAMTOR": "suppressed",
    "LARS (leucyl-tRNA synthetase)": "active", "PRAS40": "suppressed",
    "mTORC1": "active", "S6K1": "active", "4E-BP1": "suppressed",
    "ULK1": "suppressed", "TFEB": "suppressed", "SREBP1 / SREBP2": "active",
    "PDCD4": "suppressed", "eIF4E": "active",
    "Protein synthesis": "active", "Muscle growth": "active", "Lipid synthesis": "active",
    "Mitochondrial biogenesis": "active", "Nucleotide synthesis": "active",
    "Autophagy": "suppressed", "Longevity": "suppressed",
}

# Edges/nodes where a literal active<->suppressed mirror would overclaim for
# Fasting -- excluded from the mirror and left unevaluated (na) instead.
FASTING_EDGE_OVERRIDE = {"IRS1-PI3K": None}
FASTING_NODE_OVERRIDE = {}

FLIP = {"active": "suppressed", "suppressed": "active"}


def mirror(d, overrides):
    out = {}
    for k, v in d.items():
        if k in overrides:
            if overrides[k] is not None:
                out[k] = overrides[k]
            continue
        out[k] = FLIP.get(v, v)
    return out


FASTING_EDGES = mirror(FED_EDGES, FASTING_EDGE_OVERRIDE)
FASTING_NODES = mirror(FED_NODES, FASTING_NODE_OVERRIDE)

# ---------------------------------------------------------------------------
# EXERCISE -- hand-curated, acute bout. Not a mirror of anything.
# ---------------------------------------------------------------------------
EXERCISE_EDGES = {
    # energy / mechanical arm -- the exercise-defining arm
    "STRESS-AMPK": "active", "LKB1-AMPK": "active", "AMPK-ULK1": "active",
    "AMPK-MITOPHAGY": "active", "AMPK-TSC": "active", "AMPK-MTORC1": "active",
    "TSC-RHEB": "active", "RHEB-MTORC1": "suppressed",
    # growth-factor / amino-acid arm -- genuinely unresolved acutely
    "IGF1-PI3K": "unclear", "PI3K-AKT": "unclear", "AKT-TSC": "unclear",
    "AKT-PRAS40": "unclear", "PRAS40-MTORC1": "unclear",
    "LEU-SESN2": "unclear", "LEU-LARS": "unclear", "SESN2-GATOR2": "unclear",
    "ARG-CASTOR1": "unclear", "CASTOR1-GATOR2": "unclear",
    "SAM-SAMTOR": "unclear", "SAMTOR-GATOR1": "unclear",
    "GATOR2-GATOR1": "unclear", "GATOR1-RAG": "unclear",
    "LARS-RAG": "unclear", "SLC38A9-RAG": "unclear", "GLN-RAG": "unclear",
    "RAG-MTORC1": "unclear",
    # effector / output arm -- suppressed acutely (mTORC1 down)
    "MTORC1-S6K1": "suppressed", "MTORC1-4EBP1": "suppressed", "MTORC1-TFEB": "suppressed",
    "MTORC1-ULK1": "suppressed", "MTORC1-SREBP": "suppressed", "S6K1-PDCD4": "suppressed",
    "4EBP1-EIF4E": "active", "PDCD4-TRANSL": "active", "EIF4E-TRANSL": "suppressed",
    "TRANSL-MUSCLE": "suppressed",
    "TFEB-AUTOPHAGY": "active", "ULK1-AUTOPHAGY": "active",
    "SREBP-LIPID": "suppressed", "MTORC1-NUCL": "suppressed", "S6K1-NUCL": "suppressed",
    "4EBP1-LONGEVITY": "active", "S6K1-LONGEVITY": "suppressed",
}
EXERCISE_NODES = {
    "Energy & cellular stress": "active", "AMPK": "active", "LKB1 (STK11)": "active",
    "TSC1/TSC2": "active", "Rheb": "suppressed", "mTORC1": "suppressed",
    "Growth hormone / IGF-1 axis": "unclear", "PI3K": "unclear", "Akt/PKB": "unclear",
    "PRAS40": "unclear", "Leucine": "unclear", "Arginine": "unclear",
    "S-adenosylmethionine (SAM)": "unclear", "Glutamine": "unclear",
    "Rag GTPases": "unclear", "GATOR1": "unclear", "GATOR2": "unclear",
    "Sestrin2": "unclear", "CASTOR1": "unclear", "SAMTOR": "unclear",
    "LARS (leucyl-tRNA synthetase)": "unclear", "SLC38A9": "unclear",
    "S6K1": "suppressed", "4E-BP1": "active", "ULK1": "active", "TFEB": "active",
    "SREBP1 / SREBP2": "suppressed", "PDCD4": "active", "eIF4E": "suppressed",
    "Protein synthesis": "suppressed", "Muscle growth": "unclear",
    "Nucleotide synthesis": "suppressed", "Autophagy": "active", "Longevity": "active",
}

STUBS = {
    "cancer": {
        "cluster": "disease",
        "label": "Cancer",
        "brief": "Not yet curated. Needs a different annotation than flux-state: which nodes are "
                 "recurrently altered (TSC1/2 loss, PTEN loss, S6K amplification) rather than "
                 "transiently on or off. Planned as a separate curation pass over this corpus's "
                 "cancer-tagged studies.",
    },
    "aging": {
        "cluster": "disease",
        "label": "Aging",
        "brief": "Not yet curated. Chronic low-grade activation is not a discrete on/off state -- "
                 "needs its own visual language, most likely a gradient rather than active/suppressed. "
                 "MTORC1-SENESCENCE and related chronic-timescale edges were deliberately left "
                 "unevaluated in Fed/Fasting/Exercise pending this pass.",
    },
    "muscle": {
        "cluster": "tissue",
        "label": "Muscle",
        "brief": "Not yet curated. Requires a dedicated tissue-specific literature pass -- which nodes "
                 "and isoforms are muscle-enriched -- rather than reweighting the existing generic map.",
    },
    "immune": {
        "cluster": "tissue",
        "label": "Immune cell",
        "brief": "Not yet curated. Same scope as Muscle: a separate curation sprint over a smaller, "
                 "tissue-specific node subset.",
    },
    "neuron": {
        "cluster": "tissue",
        "label": "Neuron",
        "brief": "Not yet curated. Local translation at synapses needs sourcing distinct from the rest "
                 "of this map.",
    },
}


def build():
    contexts = []
    contexts.append({
        "id": "all", "cluster": "state", "stub": False, "label": "All (no filter)",
        "brief": "Default view, no context weighting applied. All interactions render at standard "
                 "evidence-tier styling, exactly as today.",
        "note": "", "edges": {}, "nodes": {},
    })
    contexts.append({
        "id": "fed", "cluster": "state", "stub": False, "label": "Fed",
        "brief": "Insulin and amino acids both high. PI3K-Akt and the Rag GTPases actively drive "
                 "mTORC1; AMPK and TSC1/2 sit quiet. Net effect: the cap comes off S6K1 and 4E-BP1, "
                 "autophagy (ULK1, TFEB) stays held off.",
        "note": "", "edges": FED_EDGES, "nodes": FED_NODES,
    })
    contexts.append({
        "id": "fasting", "cluster": "state", "stub": False, "label": "Fasting",
        "brief": "Insulin and amino acids both low. AMPK and TSC1/2 take over, mTORC1 goes quiet. "
                 "4E-BP1 stays bound as a brake, ULK1 and TFEB switch on: autophagy and lysosomal "
                 "biogenesis.",
        "note": "Generated as the mirror image of Fed on the same fixed layout -- same nodes, opposite "
                "arms lit -- except IRS-1/IRS-2 to PI3K, left unevaluated rather than mirrored because "
                "releasing that feedback brake does not by itself imply active signalling when upstream "
                "growth-factor input is also low.",
        "edges": FASTING_EDGES, "nodes": FASTING_NODES,
    })
    contexts.append({
        "id": "exercise", "cluster": "state", "stub": False, "label": "Exercise",
        "brief": "Mechanical and energy stress drive AMPK hard; growth-factor and amino-acid input are "
                 "genuinely unclear in this acute window rather than simply off. mTORC1 is suppressed "
                 "acutely; autophagy runs.",
        "note": "Acute bout shown. Post-exercise refeeding reactivates mTORC1 via the mechanical + "
                "amino-acid route, which this snapshot does not model. Mitochondrial biogenesis is left "
                "unevaluated here (na) rather than marked suppressed: this corpus's mTORC1-MITO edge is "
                "not the dominant exercise-driven route (that runs through AMPK/PGC-1alpha, not curated "
                "as a distinct edge yet), so scoring it off this edge alone would overclaim.",
        "edges": EXERCISE_EDGES, "nodes": EXERCISE_NODES,
    })
    for cid, spec in STUBS.items():
        contexts.append({
            "id": cid, "cluster": spec["cluster"], "stub": True, "label": spec["label"],
            "brief": spec["brief"], "note": "", "edges": {}, "nodes": {},
        })
    return {
        "meta": {
            "version": "1.0.0",
            "source_of_truth": "pathway/contexts.json (generated by build_pathway_contexts.py, "
                                "overlay on pathway/model.json -- never hand-edited)",
            "vocab": {
                "state": ["active", "suppressed", "unclear"],
                "cluster": ["state", "disease", "tissue"],
            },
            "caveat": "Reads as directional emphasis within this curated corpus, not a quantitative "
                      "claim about flux. Node positions never move between contexts -- only weighting "
                      "changes. An id absent from a context's edges/nodes map was not evaluated for "
                      "that context and renders identically to the unfiltered baseline.",
        },
        "contexts": contexts,
    }


def validate(doc):
    errors = []
    seen_ids = set()
    for c in doc["contexts"]:
        if c["id"] in seen_ids:
            errors.append("duplicate context id " + c["id"])
        seen_ids.add(c["id"])
        for eid, state in c["edges"].items():
            if eid not in ALL_EDGE_IDS:
                errors.append(c["id"] + ": unknown edge id " + eid)
            if state not in ("active", "suppressed", "unclear"):
                errors.append(c["id"] + ": bad edge state " + eid + "=" + str(state))
        for nid, state in c["nodes"].items():
            if nid not in ALL_NODE_IDS:
                errors.append(c["id"] + ": unknown node id " + nid)
            if state not in ("active", "suppressed", "unclear"):
                errors.append(c["id"] + ": bad node state " + nid + "=" + str(state))
    return errors


if __name__ == "__main__":
    doc = build()
    errs = validate(doc)
    if errs:
        print("VALIDATION FAILED:")
        for e in errs:
            print(" -", e)
        sys.exit(1)
    print("Validation OK.")
    print("Contexts:", [c["id"] for c in doc["contexts"]])
    for c in doc["contexts"]:
        if not c["stub"] and c["id"] != "all":
            print(" ", c["id"], "edges:", len(c["edges"]), "nodes:", len(c["nodes"]))
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print("Wrote", OUT_PATH)
